services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-gymniac}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - gymniac-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    image: gymniac-server:latest
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - LOCAL_IMAGE_DIRECTORY=/app/images
      - JWT_PRIVATE_KEY_PATH=/keys/private.pem
      - JWT_PUBLIC_KEY_PATH=/keys/public.pem
    volumes:
      - api-images:/app/images
      - jwt-keys:/keys
    networks:
      - gymniac-network
  
  client:
    container_name: client
    image: gymniac-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    env_file:
      - .env
    ports:
      - 3005:3000
    networks:
      - gymniac-network
    

volumes:
  jwt-keys:
  api-images:
  postgres-data:
networks:
  gymniac-network:
    name: gymniac-network