server:
  port: 8081

spring:

  servlet:
    multipart:
      max-file-size: 1MB

  application:
    name: server

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-version: 0
    enabled: true
    baselineOnMigrate: true
    validate-on-migrate: true
    table: flyway_schema_history

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          flushMode: COMMIT

# Authentication Tokens
authentication:
  token:
    access-token:
      expiration-time: 86400 # 1 day (In seconds)
    refresh-token:
      expiration-time: 604800 # One Week (In seconds)
