server:
  port: 8082
spring:
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/gymniac

authentication:
  token:
    jwt:
      private-key: classpath:private.pem
      public-key: classpath:public.pem