server:
  port: 8082
spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/gymniac

authentication:
  token:
    jwt:
      private-key: classpath:private.pem
      public-key: classpath:public.pem