spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    show-sql: false
  flyway:
      locations: classpath:db/migration
authentication:
  token:
    jwt:
      private-key: file:${JWT_PRIVATE_KEY_PATH}
      public-key: file:${JWT_PUBLIC_KEY_PATH}

image:
  storage-dir: ${LOCAL_IMAGE_DIRECTORY}